version: '3'

services:
  node-app:
    build: .
    command: sh -c "npm install && npm run run:dev"
    environment:
      - PORT=5000
      - NODE_ENV=development
    ports:
      - '5000:5000'
    working_dir: /srv/node-app
    volumes:
      - .:/srv/node-app
